version: "3.9"
services:
  hackingtool:
    image: vgpastor/hackingtool
    container_name: hackingtool
    stdin_open: true
    tty: true
    volumes:
      - D:\Devops-challenges\Challenge-1\hackingtool:/root/hackingtool
    ports:
      - 22:22
